### ISSUE TITLE
Create Boilerplate HTML document

### ISSUE THREAD

**Issue by mikelbrierly** [developer-delta/halogen#1]
Every app has to start somewhere!

- [x] Create a brand new `index.html` file, and load it up with all the basic HTML needed to be valid.

- [x] Add a title element with the hame `halogen`

**Comment by code-reaper08** [comment]
I love to create the boilerplate. Could you assign me this ?

**Comment by mikelbrierly** [comment]
> I love to create the boilerplate. Could you assign me this ?

Hey @code-reaper08! Sorry we went ahead without you on this one, On Saturday mornings we have a beginner developer class, and use this repo as a learning tool. I'd be glad to assign you an issue in the future though if you'd like! For the next few months the issues will be very very beginner focused.

**Comment by code-reaper08** [comment]
Thanks for your reply 😃
