### ISSUE TITLE
"Demo" toggle switch feature

### ISSUE THREAD

**Issue by mikelbrierly** [developer-delta/halogen#14]
In the "Demo" section of the site, we need to add a toggle switch that matches the design. We also need to give it functionality so that toggling it switches out our picture and the opacity on the halogen UI on the right.

* Use a checkbox input as the base HTML element

* Find a way to visible change the checkbox into your custom CSS. 

* When the checkbox is in the "checked" state, style the toggle as if it were "on"

* When the checkbox is in the "unchecked" state, style the toggle as if it were "off" 

* When the checkbox is in the checked state, the opacity of the UI on the right should be darker. This could be achieved with an overlay or with black underneath it and lowering its opacity. Or your own solution!

* When the checkbox is in the checked state, the image on the left should change to the brighter image. Think about using JS to swap out the img src attribute... (lighter image is attached)

Notes:
* The toggle switch can be done without JS, but feel free to use anything you can to make it work! Google is your friend. But try to minimize copy/paste. Try and solve the puzzle yourself!
* The reason we are swapping out the image rather than just also changing its opacity is because in the real product we'll have separate pictures for different screens bouncing light in different ways.

**Comment by samleemcknight** [comment]
want me to take this?

**Comment by mikelbrierly** [comment]
100% dude!

**Comment by samleemcknight** [comment]
quick question: would you like for me to change the id's to classes?

**Comment by mikelbrierly** [comment]
Heck yeah sounds like a plan!
