### ISSUE TITLE
Create new API endpoint to return mock JSON response data

### ISSUE THREAD

**Issue by mikelbrierly** [developer-delta/halogen#156]
## User Story:

> As a developer,
I want to be able to use the mock JSON data that Rohini created,
So that we can develop dynamic data-driven functionality on the site

---

## Acceptance Criteria:

- [x] Require the `mockResponse.json` file in `server/index.js` at the top of the file.
- [x] Create a new `app.get` endpoint for "/profiles"
- [x] Send `res.json` back with the mockResponse data
- [x] Test that your new endpoint is returning the mock data by hitting localhost:3001/profiles in either the browser or with postman. You should see Rohini's mock data returned as JSON!
- [x] 🥳

**Comment by Hanna-N9** [comment]
Working as expected:
![1C184D18-433A-4620-998F-B4FFF094803F_1_105_c](https://user-images.githubusercontent.com/56139569/128252142-6a2b7f30-0fea-4975-bb23-79bb69ddd04f.jpeg)
