### ISSUE TITLE
SPIKE: Investigate unit testing framework

### ISSUE THREAD

**Issue by mikelbrierly** [developer-delta/halogen#36]
## Spike:

> As a developer,
I want to find out what the best React testing framework for the team is,
So that we can make an educated decision moving forward

---

## Acceptance Criteria:

- [x] Add a comment to this story with a quick explanation of what a unit test is, and how they help us
- [x] Investigate what the best testing framework is for our team to write unit tests in, and list some pros and cons in a comment of this Spike.
- [x] Discuss with team to decide on which we'll use
- [x] Create a new user story (issue) for implementing a couple basic unit tests

**Comment by Hanna-N9** [comment]
**Add a comment to this story with a quick explanation of what a unit test is, and how they help us**

- A unit test is a process to test a small part or unit of a program,  typically a method. Testing an extensive program can bring difficulty as multiple bugs can take time to fix and are costly. So the unit test is a benefit to test the smallest piece of code or unit independently from other program parts. In addition, the unit test brings clean code, finds bugs early, makes debugging easier, saves our time, reduces cost, and so on.

**Comment by Hanna-N9** [comment]
**Investigate what the best testing framework is for our team to write unit tests in, and list some pros and cons in a comment of this Spike:**

After doing some research, I found that the most preferred and best testing framework for JavaScript is Jest. Furthermore, Jest has been recommended as the React testing framework as a choice from folks of React community. So, just like how Facebook created React, it created the Jest framework for simplicity.

**Pros:** 
- Jest is possible the most popular testing framework for React
- An open-source
- Has features including snapshots that is used to simplify testing and prevent bugs
- Simple to setup and install, so less configuration 
- Has a good speed to test cases
- Jest is used not only for React but also for  Babel, TypeScript, Node.js, Angular, Vue.js, and Svelte

**Cons:**
- Compared to other frameworks, there are not many libraries or tools supported by Jest.
- Easy to accept snapshots that have problems
- Jest can be easy or not easy depending on a person
- Snapshot testing can be an issue for larger snapshot files

**Comment by mikelbrierly** [comment]
This is a perfect and thorough write up, thanks Hannna! I think Jest is a great option! As soon as we have the basic react app set up, I'll create a story for adding a small Jest prototype unit test to a piece of that code.
