### ISSUE TITLE
Set up sections

### ISSUE THREAD

**Issue by mikelbrierly** [developer-delta/halogen#5]
Add a `main` element to the HTML body, and structure it with 4 section elements.

- [x]  Landing section with a class attribute of "hero"

- [x] Demo section with a class of "demo"

- [x] halogen UI section with a class of "app"

- [x] Color palette carousel section with a class of "palettes"

_Note that no actual content needs to be added to these sections, this is just to layout the general structure within the  `main` element._

**Comment by samleemcknight** [comment]
I can take this
