### ISSUE TITLE
Initial page layout

### ISSUE THREAD

**Issue by mikelbrierly** [developer-delta/halogen#54]
## User Story:

> As a developer,
I want to lay out the initial JSX in an organized way,
So that developing components in the future is intuitive and easy

---

#### Update the JSX in `App.js` to reflect the sections in the attached screenshot
- [x] Use [semantic HTML elements](https://developer.mozilla.org/en-US/docs/Glossary/Semantics#semantics_in_html) whenever possible
- [x] Add an element for the navbar
- [x] Add an element for the "hero" section
- [x] Add an element for the "pitch" section (possible rename this)
- [x] Add an element for the halogen app itself
- [x] Add an element for the palette section
- [x] Add an element for the footer section

---

_Note: This story is just about setting up the containers, no content inside is needed. We will have separate stories for each sections content_

![192E9345-5149-4FCA-B599-D7A5AEE6C6C8](https://user-images.githubusercontent.com/13723156/125321063-efa56b00-e301-11eb-824b-049bd3cc8d26.jpeg)

**Comment by rohinij15** [comment]
I finished writing the sections but I kind of got a little excited and carried away and started thinking about the layout of the webapp. I just created a Google JamBoard to jot down my ideas. Maybe looking at these ideas we can prototype on a better platform like JustinMind, Figma, etc. I just wanted to write down some ideas without getting to fancy so I just did it on Jamboard. Here's the link if y'all want to check it out and maybe leave some suggestions so when we are actually designing we can refer back to these simple notes. https://jamboard.google.com/d/1p8IgGBh6N_K54cxLYsnewVA6HHIDWIng8PsfA3v3gT0/edit?usp=sharing
