### ISSUE TITLE
Application security with IP range

### ISSUE THREAD

**Issue by mikelbrierly** [developer-delta/halogen#55]
## User Story:

> As a developer,
I want to limit application access to a range of IP's,
So that our app is more secure

---

## Acceptance Criteria:

Continue with [this step](https://developer.mongodb.com/how-to/use-atlas-on-heroku/#configuring-heroku-ip-addresses-in-atlas) from the MongoDB/Heroku guide

_I think [Fixie is a good free option](https://elements.heroku.com/addons/fixie) for us, but you can choose a different one from [this list](https://elements.heroku.com/addons/categories/network) if you think it'd be better_

- [x] Follow the Heroku documentation to install the chosen IP add-on
- [x] Configure our MongoDB atlas firewall to accept connections on one of the addon IP's under the _Network Access_ tab in the Mongo dashboard
- [x] Add a small explanation of what the benefit of the work you did is as a comment to this story. (Please ask clarifying questions if you have any doubts!)

**Comment by Hanna-N9** [comment]
The benefit did allow me to use a network server that is an add-on of Heroku and connect the app to MongoDB Atlas. So, I had access to not allow access from anywhere, and Fixie as an add-on was a simple way to set up for free (I chose Tricycle-Free) and not allowing access to everyone.
