### ISSUE TITLE
Landing page "Hero" section

### ISSUE THREAD

**Issue by mikelbrierly** [developer-delta/halogen#6]
* Add a gradient to the `body` element that is fixed and doesn't scroll with the page.

* Create an `assets` directory at the base of the project.

* Add the title logo, and three device windows as `img` tags. The images should live inside the `assets` directory you just created.

* Add the appropriate copy text underneath the logo.

* Create a button element with the text content "Get Started"

_Don't worry about styling too heavily, just focus on layout at this point.
(Flexbox may be needed)_

**Comment by mikelbrierly** [comment]
![Screen Shot 2021-01-29 at 11 26 52 AM](https://user-images.githubusercontent.com/13723156/106307896-89ca9880-6225-11eb-8ff4-f23317a2e36a.png)

**Comment by mikelbrierly** [comment]
![UI Window](https://user-images.githubusercontent.com/13723156/106312791-d6fe3880-622c-11eb-905b-807e7b031700.png)

![Phone Window](https://user-images.githubusercontent.com/13723156/106312844-e9787200-622c-11eb-83e2-33b08cc5f9d5.png)

![Mac Window](https://user-images.githubusercontent.com/13723156/106312909-0319b980-622d-11eb-851e-2388d3c6ffc6.png)

**Comment by mikelbrierly** [comment]
![Halogen Title Logo](https://user-images.githubusercontent.com/13723156/106313139-5429ad80-622d-11eb-9d4c-d29ea68aa537.png)

**Comment by samleemcknight** [comment]
cool beans - I'm on it!

**Comment by mikelbrierly** [comment]
Hey Sam! All the issues are attached here as comments! You can just right click and save as. You'll need to view the issue itself, probably in a new tab

**Comment by mikelbrierly** [comment]
Ooooh you know what I just realized!! Haha if you're in light mode, you'll only see the gradient circle, because the halogen text is white. If you just save that image, it's the whole thing, just white with a transparent bg

**Comment by mikelbrierly** [comment]
![image](https://user-images.githubusercontent.com/13723156/106473326-495b5c80-6469-11eb-9579-acc9c1653581.png)

**Comment by samleemcknight** [comment]
Haha that makes so much more sense. Thanks, man!

**Comment by samleemcknight** [comment]
Sorry I keep asking questions, but should I do a mix of flex and grid, or just keep it simple and stick with flex? Or does it matter?

**Comment by mikelbrierly** [comment]
I think for this task, just flexbox should be enough! Grid could be used, But it might be a little overkill for this layout. Grid really shines when used for things like image collages or vast modular layouts. And ask away! That's what this is for!

**Comment by samleemcknight** [comment]
[https://media1.tenor.com/images/862d5ac72c5079641f5d23fcc65da3f7/tenor.gif?itemid=19424471](url)
