### ISSUE TITLE
"color palette carousel" section

### ISSUE THREAD

**Issue by mikelbrierly** [developer-delta/halogen#9]
- [ ] Create a carousel section that contains enough divs to be able to scroll horizontally.

_For now just go ahead and add some placeholder grey squares, don't worry about them being actual palettes_

**Comment by mikel-ghost** [comment]
Testing, plz ignore

**Comment by lukemccrae** [comment]
I didn't see this before I added the sliders, woops!

**Comment by mikelbrierly** [comment]
Haha no worries!
