### ISSUE TITLE
Install Nunito Sans font

### ISSUE THREAD

**Issue by mikelbrierly** [developer-delta/halogen#90]
## User Story:

> As a developer,
I want to have access to the Nunito Sans font,
So that the Halogen application more closely resembles the designs

---

## Acceptance Criteria:

- [x] Referencing [this article](https://blog.greenroots.info/3-quick-ways-to-add-fonts-to-your-react-app), decide if we should use `Web Font Loader` or just a `link` tag for the font.
- [x] Include these styles of Nunito Sans: Bold, SemiBold, Regular, Light, and  Black
- [x] Download the needed fonts from google fonts
- [x] Test that the fonts are showing up when you run the app locally

Here's how you can check the font of an element in the browser - 

![check-font](https://user-images.githubusercontent.com/13723156/126189947-7c5bbe17-5275-405a-9218-88a8e598074f.gif)

**Comment by aggarwalsshreya** [comment]
Chose font link since it looks easier to implement
